[theme]
base = "dark"
primaryColor = "#1ED760"
backgroundColor = "#121212"
secondaryBackgroundColor = "#333333"
textColor = "#FFFFFF"
linkColor = "#9D9D9D"
borderColor = "#7F7F7F"
showWidgetBorder = false
baseRadius = "0.3rem"
font = "sans serif"

[client]
showSidebarNavigation = true

[theme.sidebar]
backgroundColor = "#000000"
secondaryBackgroundColor = "#333333"
borderColor = "#696969"
